server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:changelog.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: softtestmail026@gmail.com
    password: softtestmail026123
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

email:
  from: nsu.hub@information.com